<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Hexa.NET.ImGui" Version="2.2.9" />
    <PackageVersion Include="Hexa.NET.ImNodes" Version="2.2.9" />
    <PackageVersion Include="Testably.Abstractions.FileSystem.Interface" Version="10.0.0" />
    <PackageVersion Include="ktsu.Essentials" Version="2.3.2" />
    <PackageVersion Include="ktsu.Essentials.FileSystemProviders.Native" Version="2.3.2" />
    <PackageVersion Include="ktsu.Essentials.PersistenceProviders.ConfigHome" Version="2.3.2" />
    <PackageVersion Include="ktsu.Essentials.SerializationProviders.Yaml" Version="2.3.2" />
    <PackageVersion Include="ktsu.ImGui.App" Version="3.32.0" />
    <PackageVersion Include="ktsu.UndoRedo.Core" Version="1.0.19" />
    <PackageVersion Include="ktsu.ImGui.App.Testing" Version="3.32.0" />
    <PackageVersion Include="ktsu.ImGui.SyntaxHighlighting" Version="3.32.0" />
    <PackageVersion Include="ktsu.ImGui.Probes" Version="3.32.0" />
    <PackageVersion Include="ktsu.ImGui.Widgets" Version="3.32.0" />
    <PackageVersion Include="Silk.NET.Windowing.Common" Version="2.23.0" />
    <PackageVersion Include="ktsu.ImGui.NodeEditor" Version="3.32.0" />
    <PackageVersion Include="ktsu.ForceDirectedLayout" Version="3.32.0" />
    <PackageVersion Include="ktsu.CodeBlocker" Version="2.0.4" />
    <PackageVersion Include="ktsu.DeepClone" Version="2.0.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CrashDump" Version="1.7.2" />
    <PackageVersion Include="Microsoft.Testing.Extensions.Fakes" Version="17.14.1" />
    <PackageVersion Include="Microsoft.Testing.Extensions.HangDump" Version="1.7.2" />
    <PackageVersion Include="Microsoft.Testing.Extensions.HotReload" Version="1.7.2" />
    <PackageVersion Include="Microsoft.Testing.Extensions.Retry" Version="1.7.2" />
    <PackageVersion Include="YamlDotNet" Version="16.3.0" />
    <PackageVersion Include="Polyfill" Version="10.11.0" />
  </ItemGroup>
</Project>
