// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.Coder.Test.Languages;

using System.Diagnostics;
using ktsu.Coder.Ast;
using ktsu.Coder.Languages;
using Microsoft.VisualStudio.TestTools.UnitTesting;

/// <summary>
/// Compiles what <see cref="CGenerator"/> writes, with a real C compiler.
/// </summary>
/// <remarks>
/// Every other test here pins a spelling, and a spelling can be pinned and still be wrong: C's rules
/// about what may initialise an object with static storage duration, what an empty parameter list
/// declares, and what a file-scope <c>const</c> links as are not visible in the text at all. The only
/// thing that knows them is a compiler.
/// <para>
/// The header is included twice on purpose. That is what a header is for, and it is what makes
/// <c>#pragma once</c> and the <c>static const</c> spelling of a constant load-bearing rather than
/// stylistic.
/// </para>
/// <para>
/// The test is inconclusive rather than failing where no compiler is on the path, which is the
/// honest result: nothing was checked. A hosted Linux or macOS runner has one; a Windows one usually
/// does not, and the rest of the suite covers what the text says there.
/// </para>
/// </remarks>
[TestClass]
public class CGeneratedSourceCompilesTests
{
	/// <summary>
	/// The compilers to look for, in the order a C project would.
	/// </summary>
	private static readonly string[] Compilers = ["cc", "gcc", "clang"];

	/// <summary>
	/// The consumer of the generated header, written the way a person would write one.
	/// </summary>
	/// <remarks>
	/// It uses every declaration the header makes, so a declaration that compiles on its own but
	/// cannot be used — a constant that is not a constant expression, a function pointer whose
	/// signature does not match what implements it — fails here rather than passing quietly.
	/// </remarks>
	private const string Driver = """
		#include "exemplar.h"
		#include "exemplar.h"

		static double circle_area(const void* self)
		{
			(void)self;
			return 1.0;
		}

		static void circle_draw(void* self, double scale)
		{
			(void)self;
			(void)scale;
		}

		int main(void)
		{
			Point built = Point_create(1, 2);
			Point zeroed = Point_zero();
			Origin first = origins[0];
			Shape shape = { .draw = circle_draw, .area = circle_area };
			Colour colour = Colour_Green;

			shape.draw(&built, 2.0);

			return (built.x + zeroed.y + first.y + (int)shape.area(&first) + (int)colour) * 0;
		}

		""";

	/// <summary>
	/// Tests that a header holding every kind of declaration the generator writes compiles, and that
	/// a translation unit including it twice compiles too.
	/// </summary>
	[TestMethod]
	public void GeneratedHeader_Compiles()
	{
		string? compiler = FindCompiler();
		if (compiler is null)
		{
			Assert.Inconclusive("No C compiler on the path, so nothing was compiled.");
			return;
		}

		string directory = Path.Combine(Path.GetTempPath(), $"coder-c-{Guid.NewGuid():N}");
		Directory.CreateDirectory(directory);

		try
		{
			File.WriteAllText(
				Path.Combine(directory, "exemplar.h"),
				new CGenerator().Generate(Exemplar()));
			File.WriteAllText(Path.Combine(directory, "driver.c"), Driver);

			(int exitCode, string output) = Run(
				compiler,
				$"-std=c11 -Wall -Wextra -pedantic -c driver.c -o driver.o",
				directory);

			Assert.AreEqual(0, exitCode, $"{compiler} rejected the generated header:{Environment.NewLine}{output}");
		}
		finally
		{
			Directory.Delete(directory, recursive: true);
		}
	}

	/// <summary>
	/// Builds a header holding one of everything the generator has a spelling for.
	/// </summary>
	/// <returns>The file to generate.</returns>
	private static SourceFile Exemplar()
	{
		SourceFile file = new("exemplar") { IsHeader = true };
		file.HeaderComment.Add("Generated by Coder. Do not edit.");
		file.Imports.Add("<stdbool.h>");

		EnumDeclaration colour = new("Colour") { UnderlyingType = "int" };
		colour.Documentation.Add("What something is coloured.");
		colour.Members.Add(new EnumMember("Red") { Value = "1" });
		colour.Members.Add(new EnumMember("Green"));

		ClassDeclaration point = new("Point") { Kind = TypeDeclarationKind.Struct };
		point.Documentation.Add("Somewhere on a surface.");
		point.Members.Add(new VariableDeclaration("x", "int"));
		point.Members.Add(new VariableDeclaration("y", "int", new LiteralExpression<int>(1)));

		FunctionDeclaration create = new("Point") { Kind = FunctionKind.Constructor };
		create.Parameters.Add(new Parameter("x", "int"));
		create.Parameters.Add(new Parameter("y", "int") { IsOptional = true, DefaultValue = "0" });
		create.Initialisers.Add(new MemberInitialiser("x") { Value = new VariableReference("x") });
		create.Initialisers.Add(new MemberInitialiser("y") { Value = new VariableReference("y") });
		point.Members.Add(create);

		ConstructionExpression origin = new(new TypeReference("Point"));
		origin.Arguments.Add(new MemberInitialiser("x") { Value = new LiteralExpression<int>(0) });
		origin.Arguments.Add(new MemberInitialiser("y") { Value = new LiteralExpression<int>(0) });

		FunctionDeclaration zero = new("zero") { ReturnType = "Point", IsStatic = true, IsPure = true };
		zero.Body.Add(new ReturnStatement(origin));
		point.Members.Add(zero);

		ClassDeclaration shape = new("Shape") { Kind = TypeDeclarationKind.Interface };
		shape.Documentation.Add("What every shape can do.");
		FunctionDeclaration draw = new("draw") { IsAbstract = true };
		draw.Parameters.Add(new Parameter("scale", "double"));
		shape.Members.Add(draw);
		shape.Members.Add(new FunctionDeclaration("area")
		{
			ReturnType = "double",
			IsReadOnly = true,
			IsAbstract = true,
		});

		UsingAlias origins = new() { Name = "Origin", AliasedType = "Point" };

		ConstructionExpression table = new(type: null);
		foreach (int offset in new[] { 0, 1 })
		{
			ConstructionExpression row = new(new TypeReference("Point"));
			row.Arguments.Add(new MemberInitialiser("x") { Value = new LiteralExpression<int>(offset) });
			row.Arguments.Add(new MemberInitialiser("y") { Value = new LiteralExpression<int>(offset) });
			table.Arguments.Add(row);
		}

		FieldDeclaration origin_table = new()
		{
			Name = "origins",
			Type = new TypeReference("Point") { IsArray = true, IsReadOnly = true },
			IsConstant = true,
			InitialValue = table,
		};
		origin_table.Documentation.Add("Where each shape starts.");

		file.Members.Add(colour);
		file.Members.Add(point);
		file.Members.Add(shape);
		file.Members.Add(origins);
		file.Members.Add(origin_table);
		file.Members.Add(new CompileTimeAssertion
		{
			Condition = "sizeof(Point) == 2 * sizeof(int)",
			Message = "Point must stay two ints",
		});

		return file;
	}

	/// <summary>
	/// Finds the first compiler on the path.
	/// </summary>
	/// <returns>Its name, or null when there is none.</returns>
	private static string? FindCompiler() =>
		Compilers.FirstOrDefault(compiler => Run(compiler, "--version", Path.GetTempPath()).ExitCode == 0);

	/// <summary>
	/// Runs a command, waiting for it to finish.
	/// </summary>
	/// <param name="command">The executable to run.</param>
	/// <param name="arguments">Its arguments.</param>
	/// <param name="workingDirectory">Where to run it.</param>
	/// <returns>What it exited with, and everything it wrote.</returns>
	private static (int ExitCode, string Output) Run(string command, string arguments, string workingDirectory)
	{
		ProcessStartInfo start = new(command, arguments)
		{
			WorkingDirectory = workingDirectory,
			RedirectStandardOutput = true,
			RedirectStandardError = true,
			UseShellExecute = false,
		};

		try
		{
			using Process? process = Process.Start(start);
			if (process is null)
			{
				return (-1, string.Empty);
			}

			string output = process.StandardOutput.ReadToEnd() + process.StandardError.ReadToEnd();
			process.WaitForExit();
			return (process.ExitCode, output);
		}
		catch (System.ComponentModel.Win32Exception)
		{
			// The command is not on the path, which is the answer rather than a failure.
			return (-1, string.Empty);
		}
	}
}
