// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.Coder.Test.Languages;

using ktsu.Coder.Ast;
using ktsu.Coder.Languages;
using Microsoft.VisualStudio.TestTools.UnitTesting;

/// <summary>
/// Compiles what <see cref="CppGenerator"/> writes, with a real C++ compiler.
/// </summary>
/// <remarks>
/// C, Rust and Go were each given a compile test because their rules are not visible in the text.
/// C++ was not, and the gap had a cost: an array-typed parameter came out as <c>int[] steps</c> in
/// every release until this test existed. Every pinned spelling around it passed, because a spelling
/// can be pinned and still be one a compiler refuses.
/// <para>
/// Where an array's brackets go is exactly that kind of rule. C++ has one position for them — after
/// the name being declared — and no position at all in the places that spell a type without a name,
/// so the same <see cref="TypeReference"/> is written two ways depending on where it stands. Only a
/// compiler can say whether the generator picked the right one each time.
/// </para>
/// <para>
/// The test is inconclusive rather than failing where no compiler is on the path, which is the
/// honest result: nothing was checked.
/// </para>
/// </remarks>
[TestClass]
public class CppGeneratedSourceCompilesTests
{
	/// <summary>
	/// The compilers to look for, in the order a C++ project would.
	/// </summary>
	private static readonly string[] Compilers = ["c++", "g++", "clang++"];

	/// <summary>
	/// The consumer of the generated header, which calls each declaration so that a declaration that
	/// compiles but cannot be used fails here rather than passing quietly.
	/// </summary>
	private const string Driver = """
		#include "arrays.h"

		int main()
		{
			int steps[3] = { 1, 2, 3 };
			return (Table::sum(steps, 3) + STRIDES[1]) * 0;
		}

		""";

	/// <summary>
	/// Tests that the two positions an unbounded array may stand in compile.
	/// </summary>
	/// <remarks>
	/// A parameter, and a namespace-scope constant table whose initialiser supplies the bound — which
	/// is the pair <see cref="TypeReference.IsArray"/> exists for, an array with no bound having
	/// nowhere else to stand: a data member and a local both need a bound C++ can see, and
	/// <c>IsArray</c> deliberately carries none.
	/// <para>
	/// Both are declarators, so both take the brackets after the name. The function's return type is
	/// the position with no name to put them after, and the generator has to leave them off there
	/// rather than write a type C++ cannot form.
	/// </para>
	/// </remarks>
	[TestMethod]
	public void AnArrayDeclarationCompilesWhereverAnUnboundedOneMayStand()
	{
		string? compiler = ToolchainHarness.FindOnPath("--version", Compilers);
		if (compiler is null)
		{
			Assert.Inconclusive("No C++ compiler on the path, so nothing was compiled.");
			return;
		}

		ToolchainHarness.InTemporaryDirectory(directory =>
		{
			File.WriteAllText(
				Path.Combine(directory, "arrays.h"),
				new CppGenerator().Generate(ArrayExemplar()));
			File.WriteAllText(Path.Combine(directory, "driver.cpp"), Driver);

			(int exitCode, string output) = ToolchainHarness.Run(
				compiler,
				"-std=c++20 -Wall -Wextra -pedantic -c driver.cpp -o driver.o",
				directory);

			Assert.AreEqual(0, exitCode, $"{compiler} rejected the generated header:{Environment.NewLine}{output}");
		});
	}

	/// <summary>
	/// Builds a header declaring an array in each position one with no bound may stand in.
	/// </summary>
	/// <returns>The file to generate.</returns>
	private static SourceFile ArrayExemplar()
	{
		SourceFile file = new("arrays") { IsHeader = true };
		file.HeaderComment.Add("Generated by Coder. Do not edit.");

		// A constant table, which is what IsArray was added for. The initialiser is what gives the
		// bound C++ needs, which is why this is a position an unbounded array may stand in at all.
		ConstructionExpression strides = new(type: null);
		strides.Arguments.Add(new LiteralExpression<int>(1));
		strides.Arguments.Add(new LiteralExpression<int>(2));

		FieldDeclaration table = new()
		{
			Name = "STRIDES",
			Type = new TypeReference("int") { IsArray = true, IsReadOnly = true },
			IsConstant = true,
			InitialValue = strides,
		};
		table.Documentation.Add("How far each step goes.");
		file.Members.Add(table);

		// The free function taking the array, declared before what calls it.
		file.Members.Add(Walk("walk_impl"));

		ClassDeclaration holder = new("Table") { Kind = TypeDeclarationKind.Struct };
		holder.Documentation.Add("Something taking an array through a member.");

		FunctionDeclaration sum = new("sum") { ReturnType = "int", IsStatic = true };
		sum.Parameters.Add(new Parameter("steps") { Type = new TypeReference("int") { IsArray = true } });
		sum.Parameters.Add(new Parameter("count", "int"));
		sum.Body.Add(new ReturnStatement(
			new CallExpression("walk_impl")
			{
				Arguments = { new VariableReference("steps"), new VariableReference("count") },
			}));
		holder.Members.Add(sum);

		file.Members.Add(holder);

		return file;
	}

	/// <summary>
	/// Builds a function taking an array by parameter and reading through it.
	/// </summary>
	/// <param name="name">What to call it.</param>
	/// <returns>The declaration.</returns>
	/// <remarks>
	/// The body subscripts the parameter, so the parameter's spelling is load-bearing rather than
	/// merely present: a signature nobody reads through would compile with the brackets anywhere.
	/// </remarks>
	private static FunctionDeclaration Walk(string name)
	{
		FunctionDeclaration walk = new(name) { ReturnType = "int", IsStatic = true };
		walk.Parameters.Add(new Parameter("steps") { Type = new TypeReference("int") { IsArray = true } });
		walk.Parameters.Add(new Parameter("count", "int"));
		walk.Body.Add(new ReturnStatement(
			new BinaryExpression(
				new VariableReference("steps[0]"),
				BinaryOperator.Add,
				new VariableReference("count"))));

		return walk;
	}
}
