// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.Coder.Test.Languages;

using ktsu.Coder.Ast;
using ktsu.Coder.Languages;
using Microsoft.VisualStudio.TestTools.UnitTesting;

/// <summary>
/// Builds the component from Holotype's <c>docs/generated-cpp-target.md</c> as an AST and checks that
/// the C++ generator emits the header that document specifies.
/// </summary>
/// <remarks>
/// That document is the specification for the schema compiler being moved into this stack, written as
/// its output rather than as a description of it, and its first section is byte-identical to what the
/// C++ tool it replaces emits today. So this is the acceptance test for the move: it fails if the AST
/// stops being able to describe a real generated header, rather than only if some emitter changes
/// shape.
/// <para>
/// Two differences from the document are deliberate. The <c>static_assert</c>s below the struct are
/// not here: they are an assertion about a generated type rather than something the schema asked for,
/// and where they belong is still open. And the indentation is spaces where the document has tabs,
/// which is a setting of the writer rather than anything the AST decides — Holotype's own
/// <c>.clang-format</c> reformats generated output to tabs on the way past.
/// </para>
/// </remarks>
[TestClass]
public class ExemplarHeaderTests
{
	/// <summary>The header the document specifies, less the two assertions and with tabs expanded.</summary>
	private const string Expected =
		"""
		// Generated by holo_schemac. Do not edit.
		//
		// Source: tests/schemas/rigid_body.toml
		//
		// Editing this file is editing the wrong thing: it is derived from the schema,
		// and the next build overwrites it. Change the schema instead.

		#pragma once

		#include <cstdint>
		#include <type_traits>

		#include "holotype/core/units.hpp"
		#include "holotype/core/vec.hpp"

		namespace holo::components
		{

		/// Physical state integrated by the physics system each frame.
		struct RigidBody
		{
		    enum class BodyKind : std::uint8_t
		    {
		        Static,
		        Kinematic,
		        Dynamic,
		    };

		    /// Linear velocity in world space.
		    /// unit: m/s
		    /// interpolated between states
		    /// network: quantised to 0.01, delta encoded
		    holo::Vec3<holo::MetresPerSecond> velocity{};

		    /// unit: kg
		    /// range: [0.001, 1000000]
		    holo::Kilograms mass = holo::Kilograms{ 1.0f };

		    /// unit: rad
		    /// range: [0, 6.2831853] (wraps)
		    /// network: quantised to 0.001
		    /// editor: dial
		    holo::Radians heading{};

		    /// unit: 1
		    /// range: [0, 1]
		    holo::Scalar restitution = holo::Scalar{ 0.5f };

		    BodyKind body_kind = BodyKind::Dynamic;
		};

		}  // namespace holo::components
		""";

	/// <summary>
	/// Builds the exemplar's component as an AST.
	/// </summary>
	/// <returns>The file.</returns>
	private static SourceFile RigidBodyHeader()
	{
		EnumDeclaration bodyKind = new("BodyKind") { UnderlyingType = "std::uint8_t" };
		bodyKind.Members.Add(new EnumMember("Static"));
		bodyKind.Members.Add(new EnumMember("Kinematic"));
		bodyKind.Members.Add(new EnumMember("Dynamic"));

		ClassDeclaration rigidBody = new("RigidBody") { Kind = TypeDeclarationKind.Struct };
		rigidBody.Documentation.Add("Physical state integrated by the physics system each frame.");
		rigidBody.Members.Add(bodyKind);

		rigidBody.Members.Add(Field(
			"velocity",
			"holo::Vec3<holo::MetresPerSecond>",
			null,
			"Linear velocity in world space.",
			"unit: m/s",
			"interpolated between states",
			"network: quantised to 0.01, delta encoded"));

		rigidBody.Members.Add(Field(
			"mass",
			"holo::Kilograms",
			"holo::Kilograms{ 1.0f }",
			"unit: kg",
			"range: [0.001, 1000000]"));

		rigidBody.Members.Add(Field(
			"heading",
			"holo::Radians",
			null,
			"unit: rad",
			"range: [0, 6.2831853] (wraps)",
			"network: quantised to 0.001",
			"editor: dial"));

		rigidBody.Members.Add(Field(
			"restitution",
			"holo::Scalar",
			"holo::Scalar{ 0.5f }",
			"unit: 1",
			"range: [0, 1]"));

		rigidBody.Members.Add(Field("body_kind", "BodyKind", "BodyKind::Dynamic"));

		NamespaceDeclaration components = new("holo::components");
		components.Members.Add(rigidBody);

		SourceFile file = new("RigidBody.gen.hpp") { IsHeader = true };
		file.HeaderComment.Add("Generated by holo_schemac. Do not edit.");
		file.HeaderComment.Add("");
		file.HeaderComment.Add("Source: tests/schemas/rigid_body.toml");
		file.HeaderComment.Add("");
		file.HeaderComment.Add("Editing this file is editing the wrong thing: it is derived from the schema,");
		file.HeaderComment.Add("and the next build overwrites it. Change the schema instead.");

		file.Imports.Add("<cstdint>");
		file.Imports.Add("<type_traits>");
		file.Imports.Add("");
		file.Imports.Add("holotype/core/units.hpp");
		file.Imports.Add("holotype/core/vec.hpp");
		file.Members.Add(components);

		return file;
	}

	/// <summary>
	/// Builds one field of the component.
	/// </summary>
	/// <param name="name">The field's name.</param>
	/// <param name="type">The field's type.</param>
	/// <param name="initialiser">What it starts at, or null for the type's own default.</param>
	/// <param name="documentation">The lines above it.</param>
	/// <returns>The field.</returns>
	/// <remarks>
	/// The initialiser is a <see cref="VariableReference"/> holding the construction as written. The
	/// AST has no node for constructing a value yet, which is the next thing the document asks for and
	/// the reason the two initialised fields here read as they do.
	/// </remarks>
	private static FieldDeclaration Field(
		string name,
		string type,
		string? initialiser,
		params string[] documentation)
	{
		FieldDeclaration field = new(name, type)
		{
			InitialValue = initialiser is null ? null : new VariableReference(initialiser),
		};

		foreach (string line in documentation)
		{
			field.Documentation.Add(line);
		}

		return field;
	}

	/// <summary>
	/// The generated header is the one the document specifies.
	/// </summary>
	[TestMethod]
	public void Cpp_GeneratesTheHeaderTheDocumentSpecifies() =>
		Assert.AreEqual(
			Expected.ReplaceLineEndings("\n").TrimEnd(),
			new CppGenerator().Generate(RigidBodyHeader()).ReplaceLineEndings("\n").TrimEnd());

	/// <summary>
	/// Field order is struct layout, so it is the one thing about the output that is not cosmetic.
	/// </summary>
	/// <remarks>
	/// Alphabetically these would be body_kind, heading, mass, restitution, velocity. Holotype's own
	/// schema notes record catching exactly that in a parser whose tables were sorted, and record why
	/// it matters: renaming a field would silently move it and change the binary layout of every save
	/// file and every packet carrying the component.
	/// </remarks>
	[TestMethod]
	public void Cpp_KeepsFieldsInDeclarationOrder()
	{
		string code = new CppGenerator().Generate(RigidBodyHeader());

		int previous = -1;
		foreach (string name in (string[])["velocity", "mass", "heading", "restitution", "body_kind"])
		{
			int position = code.IndexOf($" {name}", StringComparison.Ordinal);

			Assert.IsGreaterThan(previous, position, $"{name} is out of declaration order");
			previous = position;
		}
	}
}
