// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.Coder.Test.Languages;

using ktsu.Coder.Ast;
using ktsu.Coder.Languages;
using Microsoft.VisualStudio.TestTools.UnitTesting;

/// <summary>
/// Compiles what <see cref="RustGenerator"/> writes, with a real Rust compiler.
/// </summary>
/// <remarks>
/// The C generator earned a test like this because C's rules about linkage and constant expressions
/// are invisible in the text. Rust's reason is larger: a receiver that should have been
/// <c>&amp;mut self</c>, an associated item carrying a visibility it is not allowed, a trait
/// implementation missing the <c>Output</c> it has to name, a <c>const</c> that cannot be one —
/// each of those is a spelling a test can pin and a compiler rejects, and only one of them notices.
/// <para>
/// The exemplar is compiled as a library rather than run, because what is being checked is that the
/// declarations are well formed, not what they compute. The lint that fires on the output is allowed
/// by name at the top of the file rather than by silencing everything: parentheses come from the
/// AST carrying no operator precedence, which is a property of the AST rather than a mistake in this
/// generator.
/// </para>
/// <para>
/// The test is inconclusive rather than failing where no compiler is on the path, which is the
/// honest result: nothing was checked.
/// </para>
/// </remarks>
[TestClass]
public class RustGeneratedSourceCompilesTests
{
	/// <summary>
	/// Tests that a file holding one of everything the generator writes compiles.
	/// </summary>
	[TestMethod]
	public void GeneratedSource_Compiles()
	{
		if (ToolchainHarness.FindOnPath("--version", "rustc") is null)
		{
			Assert.Inconclusive("No Rust compiler on the path, so nothing was compiled.");
			return;
		}

		ToolchainHarness.InTemporaryDirectory(directory =>
		{
			// The AST carries no operator precedence, so every binary expression is parenthesised and
			// Rust says so. The lints are named rather than blanket-silenced: each one is a property
			// of what an exemplar is — declarations nothing calls, holding values nothing reads.
			string source = new RustGenerator().Generate(Exemplar());
			string allowed = "#![allow(unused_parens, dead_code, unused_variables, unused_mut)]";

			File.WriteAllText(
				Path.Combine(directory, "exemplar.rs"),
				$"{allowed}{Environment.NewLine}{source}");

			(int exitCode, string output) = ToolchainHarness.Run(
				"rustc",
				"--crate-type lib --edition 2021 -o exemplar.rlib exemplar.rs",
				directory);

			Assert.AreEqual(0, exitCode, $"rustc rejected the generated source:{Environment.NewLine}{output}");
		});
	}

	/// <summary>
	/// Builds a file holding one of everything the generator has a spelling for.
	/// </summary>
	/// <returns>The file to generate.</returns>
	private static SourceFile Exemplar()
	{
		SourceFile file = new("exemplar");
		file.HeaderComment.Add("Generated by Coder. Do not edit.");

		ClassDeclaration point = CompiledExemplar.Point();
		point.Members.Add(CompiledExemplar.Sum("sum"));
		point.Members.Add(CompiledExemplar.Shift("shift"));
		point.Members.Add(CompiledExemplar.Plus());
		point.Members.Add(CompiledExemplar.Negate());
		point.Members.Add(CompiledExemplar.ToDouble("value.x as f64"));
		point.Members.Add(CompiledExemplar.Pick("pick", "shift"));

		ClassDeclaration circle = new("Circle") { BaseType = "Point" };
		circle.Documentation.Add("A shape with one radius.");
		circle.Members.Add(new VariableDeclaration("radius", "double"));

		FunctionDeclaration drop = new("Circle") { Kind = FunctionKind.Destructor };
		drop.Body.Add(new VariableDeclaration("going", "bool", new LiteralExpression<bool>(true)));
		circle.Members.Add(drop);

		NamespaceDeclaration geometry = new("geo.shapes");
		geometry.Members.Add(CompiledExemplar.Colour());
		geometry.Members.Add(point);
		geometry.Members.Add(CompiledExemplar.Shape());
		geometry.Members.Add(circle);
		geometry.Members.Add(Describe());
		geometry.Members.Add(DescribesPoint());
		geometry.Members.Add(CompiledExemplar.OriginAlias());
		geometry.Members.Add(CompiledExemplar.OriginTable());
		geometry.Members.Add(CompiledExemplar.Measure());
		geometry.Members.Add(Boxed());
		geometry.Members.Add(new CompileTimeAssertion
		{
			Condition = "std::mem::size_of::<i32>() == 4",
			Message = "an i32 is four bytes",
		});

		file.Members.Add(geometry);
		return file;
	}

	/// <summary>
	/// A type written over one parameter, so its impl block has to carry the parameter too.
	/// </summary>
	/// <returns>The declaration.</returns>
	/// <remarks>
	/// The whole of what makes this worth compiling: a generic struct's inherent impl has to repeat
	/// the parameter and bound it — <c>impl&lt;T: Clone&gt; Boxed&lt;T&gt;</c> — and a generator
	/// that wrote <c>impl Boxed</c> beside a <c>struct Boxed&lt;T&gt;</c> would produce something
	/// that reads correctly and does not build. The bound is load-bearing rather than decoration:
	/// without it the body's call to <c>clone</c> does not resolve.
	/// </remarks>
	private static ClassDeclaration Boxed()
	{
		ClassDeclaration boxed = new("Boxed") { Kind = TypeDeclarationKind.Struct };
		boxed.Documentation.Add("Holds one of whatever it was given.");
		boxed.TypeParameters.Add(TypeParameter.Parse("T : Clone"));
		boxed.Members.Add(new FieldDeclaration("held", "T"));

		FunctionDeclaration copy = new("copy") { ReturnType = "T", IsReadOnly = true };
		copy.Body.Add(new ReturnStatement(
			new CallExpression(new VariableReference("self.held"), "clone")));
		boxed.Members.Add(copy);

		return boxed;
	}

	/// <summary>
	/// Builds a trait whose constant every implementation has to supply.
	/// </summary>
	/// <returns>The declaration.</returns>
	private static ClassDeclaration Describe()
	{
		ClassDeclaration describe = new("Describe") { Kind = TypeDeclarationKind.Interface };
		describe.Documentation.Add("What a type says about itself.");
		describe.Members.Add(new FieldDeclaration { Name = "NAME", Type = BorrowedString() });
		return describe;
	}

	/// <summary>
	/// Builds the declaration that is for a type rather than of one.
	/// </summary>
	/// <returns>The declaration.</returns>
	private static ClassDeclaration DescribesPoint()
	{
		ClassDeclaration specialisation = new("Describe")
		{
			SpecialisationArguments = { new TypeReference("Point") },
		};

		specialisation.Members.Add(new FieldDeclaration
		{
			Name = "NAME",
			Type = BorrowedString(),
			InitialValue = new LiteralExpression<string>("Point"),
		});

		return specialisation;
	}

	/// <summary>
	/// Gets a string the holder does not own, which is the one Rust asks for wherever it is only read.
	/// </summary>
	/// <returns>The type.</returns>
	private static TypeReference BorrowedString() =>
		new("str") { Indirection = TypeIndirection.Reference, IsReadOnly = true };
}
