// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.Coder.Test.Languages;

using ktsu.Coder.Ast;
using ktsu.Coder.Languages;
using Microsoft.VisualStudio.TestTools.UnitTesting;

/// <summary>
/// Compiles what <see cref="RustGenerator"/> writes, with a real Rust compiler.
/// </summary>
/// <remarks>
/// The C generator earned a test like this because C's rules about linkage and constant expressions
/// are invisible in the text. Rust's reason is larger: a receiver that should have been
/// <c>&amp;mut self</c>, an associated item carrying a visibility it is not allowed, a trait
/// implementation missing the <c>Output</c> it has to name, a <c>const</c> that cannot be one —
/// each of those is a spelling a test can pin and a compiler rejects, and only one of them notices.
/// <para>
/// The exemplar is compiled as a library rather than run, because what is being checked is that the
/// declarations are well formed, not what they compute. The lint that fires on the output is allowed
/// by name at the top of the file rather than by silencing everything: parentheses come from the
/// AST carrying no operator precedence, which is a property of the AST rather than a mistake in this
/// generator.
/// </para>
/// <para>
/// The test is inconclusive rather than failing where no compiler is on the path, which is the
/// honest result: nothing was checked.
/// </para>
/// </remarks>
[TestClass]
public class RustGeneratedSourceCompilesTests
{
	/// <summary>
	/// Tests that a file holding one of everything the generator writes compiles.
	/// </summary>
	[TestMethod]
	public void GeneratedSource_Compiles()
	{
		if (ToolchainHarness.FindOnPath("rustc") is null)
		{
			Assert.Inconclusive("No Rust compiler on the path, so nothing was compiled.");
			return;
		}

		ToolchainHarness.InTemporaryDirectory(directory =>
		{
			// The AST carries no operator precedence, so every binary expression is parenthesised and
			// Rust says so. The lints are named rather than blanket-silenced: each one is a property
			// of what an exemplar is — declarations nothing calls, holding values nothing reads.
			string source = new RustGenerator().Generate(Exemplar());
			string allowed = "#![allow(unused_parens, dead_code, unused_variables, unused_mut)]";

			File.WriteAllText(
				Path.Combine(directory, "exemplar.rs"),
				$"{allowed}{Environment.NewLine}{source}");

			(int exitCode, string output) = ToolchainHarness.Run(
				"rustc",
				"--crate-type lib --edition 2021 -o exemplar.rlib exemplar.rs",
				directory);

			Assert.AreEqual(0, exitCode, $"rustc rejected the generated source:{Environment.NewLine}{output}");
		});
	}

	/// <summary>
	/// Builds a file holding one of everything the generator has a spelling for.
	/// </summary>
	/// <returns>The file to generate.</returns>
	private static SourceFile Exemplar()
	{
		SourceFile file = new("exemplar");
		file.HeaderComment.Add("Generated by Coder. Do not edit.");

		ClassDeclaration point = CompiledExemplar.Point();
		point.Members.Add(Sum());
		point.Members.Add(Shift());
		point.Members.Add(Plus());
		point.Members.Add(Negate());
		point.Members.Add(ToDouble());

		ClassDeclaration circle = new("Circle") { BaseType = "Point" };
		circle.Documentation.Add("A shape with one radius.");
		circle.Members.Add(new VariableDeclaration("radius", "double"));

		FunctionDeclaration drop = new("Circle") { Kind = FunctionKind.Destructor };
		drop.Body.Add(new VariableDeclaration("going", "bool", new LiteralExpression<bool>(true)));
		circle.Members.Add(drop);

		NamespaceDeclaration geometry = new("geo.shapes");
		geometry.Members.Add(CompiledExemplar.Colour());
		geometry.Members.Add(point);
		geometry.Members.Add(CompiledExemplar.Shape());
		geometry.Members.Add(circle);
		geometry.Members.Add(Describe());
		geometry.Members.Add(DescribesPoint());
		geometry.Members.Add(CompiledExemplar.OriginAlias());
		geometry.Members.Add(CompiledExemplar.OriginTable());
		geometry.Members.Add(Measure());
		geometry.Members.Add(new CompileTimeAssertion
		{
			Condition = "std::mem::size_of::<i32>() == 4",
			Message = "an i32 is four bytes",
		});

		file.Members.Add(geometry);
		return file;
	}

	/// <summary>
	/// Builds a member that reads the instance without modifying it.
	/// </summary>
	/// <returns>The declaration.</returns>
	private static FunctionDeclaration Sum()
	{
		FunctionDeclaration sum = new("sum") { ReturnType = "int", IsReadOnly = true, IsPure = true };
		sum.Body.Add(new ReturnStatement(new BinaryExpression(
			new VariableReference("self.x"), BinaryOperator.Add, new VariableReference("self.y"))));
		return sum;
	}

	/// <summary>
	/// Builds a member that modifies the instance, which is what earns it a mutable receiver.
	/// </summary>
	/// <returns>The declaration.</returns>
	private static FunctionDeclaration Shift()
	{
		FunctionDeclaration shift = new("shift");
		shift.Parameters.Add(new Parameter("dx", "int"));
		shift.Body.Add(new AssignmentStatement(
			new VariableReference("self.x"), new VariableReference("dx"), AssignmentOperator.AddAssign));
		return shift;
	}

	/// <summary>
	/// Builds the binary operator, which has to become a trait implementation naming its output.
	/// </summary>
	/// <returns>The declaration.</returns>
	private static FunctionDeclaration Plus()
	{
		FunctionDeclaration plus = new("+") { Kind = FunctionKind.Operator, ReturnType = "Point" };
		plus.Parameters.Add(new Parameter("rhs", "Point"));
		plus.Body.Add(new ReturnStatement(Combined("rhs")));
		return plus;
	}

	/// <summary>
	/// Builds the unary operator that shares its symbol with the binary one.
	/// </summary>
	/// <returns>The declaration.</returns>
	private static FunctionDeclaration Negate()
	{
		FunctionDeclaration negate = new("-") { Kind = FunctionKind.Operator, ReturnType = "Point" };
		negate.Body.Add(new ReturnStatement(Combined(null)));
		return negate;
	}

	/// <summary>
	/// Builds the value an operator answers with.
	/// </summary>
	/// <param name="operand">The operand to combine each member with, or null to negate it.</param>
	/// <returns>The expression.</returns>
	private static ConstructionExpression Combined(string? operand)
	{
		ConstructionExpression built = new(new TypeReference("Point"));

		foreach (string member in new[] { "x", "y" })
		{
			Expression value = operand is null
				? new UnaryExpression(UnaryOperator.Negate, new VariableReference($"self.{member}"))
				: new BinaryExpression(
					new VariableReference($"self.{member}"),
					BinaryOperator.Add,
					new VariableReference($"{operand}.{member}"));

			built.Arguments.Add(new MemberInitialiser(member) { Value = value });
		}

		return built;
	}

	/// <summary>
	/// Builds the conversion, which has to become an implementation of <c>From</c>.
	/// </summary>
	/// <returns>The declaration.</returns>
	private static FunctionDeclaration ToDouble()
	{
		FunctionDeclaration conversion = new("ignored")
		{
			Kind = FunctionKind.ConversionOperator,
			ReturnType = "double",
			IsReadOnly = true,
		};
		conversion.Body.Add(new ReturnStatement(new VariableReference("value.x as f64")));
		return conversion;
	}

	/// <summary>
	/// Builds a trait whose constant every implementation has to supply.
	/// </summary>
	/// <returns>The declaration.</returns>
	private static ClassDeclaration Describe()
	{
		ClassDeclaration describe = new("Describe") { Kind = TypeDeclarationKind.Interface };
		describe.Documentation.Add("What a type says about itself.");
		describe.Members.Add(new FieldDeclaration { Name = "NAME", Type = BorrowedString() });
		return describe;
	}

	/// <summary>
	/// Builds the declaration that is for a type rather than of one.
	/// </summary>
	/// <returns>The declaration.</returns>
	private static ClassDeclaration DescribesPoint()
	{
		ClassDeclaration specialisation = new("Describe")
		{
			SpecialisationArguments = { new TypeReference("Point") },
		};

		specialisation.Members.Add(new FieldDeclaration
		{
			Name = "NAME",
			Type = BorrowedString(),
			InitialValue = new LiteralExpression<string>("Point"),
		});

		return specialisation;
	}

	/// <summary>
	/// Builds a free function taking a borrow and a sequence, and declaring two locals.
	/// </summary>
	/// <returns>The declaration.</returns>
	private static FunctionDeclaration Measure()
	{
		FunctionDeclaration measure = new("measure") { ReturnType = "int" };
		measure.Parameters.Add(new Parameter("label") { Type = BorrowedString() });
		measure.Parameters.Add(new Parameter("sizes")
		{
			Type = new TypeReference("list") { TypeArguments = { new TypeReference("int") } },
		});

		measure.Body.Add(new VariableDeclaration("total", "int", new LiteralExpression<int>(0)));
		measure.Body.Add(new VariableDeclaration("guessed", null, new LiteralExpression<int>(1)) { IsTypeInferred = true });
		measure.Body.Add(new ReturnStatement(new VariableReference("total")));

		return measure;
	}

	/// <summary>
	/// Gets a string the holder does not own, which is the one Rust asks for wherever it is only read.
	/// </summary>
	/// <returns>The type.</returns>
	private static TypeReference BorrowedString() =>
		new("str") { Indirection = TypeIndirection.Reference, IsReadOnly = true };
}
