// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.Coder.Test.Languages;

using System.Linq;
using ktsu.Coder.Ast;
using ktsu.Coder.Languages;
using Microsoft.VisualStudio.TestTools.UnitTesting;

/// <summary>
/// Tests that a string literal holding a trigraph keeps its value in C and C++.
/// </summary>
/// <remarks>
/// C up to C17, and C++ before C++17, replace <c>??!</c>, <c>??/</c> and the other trigraphs even
/// inside a string literal, so <c>"what??!"</c> compiled with <c>-std=c11</c> prints <c>what|</c>.
/// </remarks>
[TestClass]
public class StringLiteralTrigraphTests
{
	/// <summary>
	/// Every trigraph, a run of three question marks, and a lone one that needs no escape.
	/// </summary>
	private const string Value = "what??! a??/b ??=??'??(??)??<??>??- ???! ok?";

	/// <summary>
	/// The compilers to look for, in the order a C project would.
	/// </summary>
	private static readonly string[] Compilers = ["cc", "gcc", "clang"];

	/// <summary>
	/// Tests that C and C++ escape the second question mark of every pair, and nothing else.
	/// </summary>
	/// <param name="language">The generator's language identifier.</param>
	[TestMethod]
	[DataRow("c")]
	[DataRow("cpp")]
	public void CFamilyBreaksEveryTrigraph(string language)
	{
		ILanguageGenerator generator = Generators().Single(g => g.LanguageId == language);

		string code = generator.Generate(Literal.Text(Value));

		Assert.Contains(
			@"""what?\?! a?\?/b ?\?=?\?'?\?(?\?)?\?<?\?>?\?- ?\?\?! ok?""",
			code,
			StringComparison.Ordinal,
			$"{language} wrote {code}");
		Assert.DoesNotContain("??", code, StringComparison.Ordinal, $"{language} left a trigraph in {code}");
	}

	/// <summary>
	/// Tests that the languages without trigraphs write the question marks as they are, since
	/// <c>\?</c> is not an escape in Go, Rust or JavaScript.
	/// </summary>
	/// <param name="language">The generator's language identifier.</param>
	[TestMethod]
	[DataRow("csharp")]
	[DataRow("javascript")]
	[DataRow("python")]
	[DataRow("go")]
	[DataRow("rust")]
	public void OtherLanguagesWriteQuestionMarksAsIs(string language)
	{
		ILanguageGenerator generator = Generators().Single(g => g.LanguageId == language);

		string code = generator.Generate(Literal.Text(Value));

		Assert.Contains($"\"{Value}\"", code, StringComparison.Ordinal, $"{language} wrote {code}");
	}

	/// <summary>
	/// Tests that the generated literals hold exactly the characters they were given once a C compiler
	/// in a strict standard mode, where trigraphs are on, has read them.
	/// </summary>
	[TestMethod]
	public void CompiledWithTrigraphsOn_TheStringsKeepTheirValue()
	{
		string? compiler = ToolchainHarness.FindOnPath("--version", Compilers);
		if (compiler is null)
		{
			Assert.Inconclusive("No C compiler on the path, so nothing was compiled.");
			return;
		}

		ToolchainHarness.InTemporaryDirectory(directory =>
		{
			File.WriteAllText(Path.Combine(directory, "messages.h"), new CGenerator().Generate(Exemplar()));

			// The driver spells the expected text one character at a time, so it holds no trigraph of
			// its own, and reports which string differed through the exit code.
			File.WriteAllText(Path.Combine(directory, "driver.c"), """
				#include <string.h>
				#include "messages.h"

				int main(void)
				{
					static const char exclaim[] = { 'w', 'h', 'a', 't', '?', '?', '!', 0 };
					static const char slash[] = { 'a', '?', '?', '/', 'b', 0 };

					if (strcmp(Messages_exclaim(), exclaim) != 0)
					{
						return 1;
					}

					if (strcmp(Messages_slash(), slash) != 0)
					{
						return 2;
					}

					return 0;
				}

				""");

			(int exitCode, string output) = ToolchainHarness.Run(
				compiler,
				"-std=c11 -Wall -Wextra -pedantic -Werror=trigraphs driver.c -o driver",
				directory);
			Assert.AreEqual(0, exitCode, $"{compiler} rejected the generated literals:{Environment.NewLine}{output}");

			(int runExit, string runOutput) = ToolchainHarness.Run(Path.Combine(directory, "driver"), string.Empty, directory);
			Assert.AreEqual(0, runExit, $"String {runExit} changed value under trigraph replacement.{Environment.NewLine}{runOutput}");
		});
	}

	/// <summary>
	/// Builds a header whose two static members return a literal holding a trigraph.
	/// </summary>
	/// <returns>The file to generate.</returns>
	private static SourceFile Exemplar()
	{
		SourceFile file = new("messages") { IsHeader = true };
		file.HeaderComment.Add("Generated by Coder. Do not edit.");

		ClassDeclaration messages = new("Messages") { Kind = TypeDeclarationKind.Struct };
		messages.Documentation.Add("Literals that hold a trigraph.");
		messages.Members.Add(new VariableDeclaration("unused", "int"));

		FunctionDeclaration exclaim = new("exclaim") { ReturnType = "string", IsStatic = true };
		exclaim.Body.Add(new ReturnStatement(new LiteralExpression<string>("what??!")));
		messages.Members.Add(exclaim);

		FunctionDeclaration slash = new("slash") { ReturnType = "string", IsStatic = true };
		slash.Body.Add(new ReturnStatement(new LiteralExpression<string>("a??/b")));
		messages.Members.Add(slash);

		file.Members.Add(messages);
		return file;
	}

	private static ILanguageGenerator[] Generators() =>
	[
		new CSharpGenerator(),
		new CGenerator(),
		new CppGenerator(),
		new GoGenerator(),
		new RustGenerator(),
		new PythonGenerator(),
		new JavaScriptGenerator(),
	];
}
